image: gradle:alpine

#image: maven:3.9.9-openjdk-11

default:
  tags:
    - BackgroundAutoTestsAIM

stages:
  - test

Integration tests with Allure:
  stage: test
  script:
    - ./gradlew clean test
    - ./gradlew allureReport
  artifacts:
    paths:
      - build/reports/allure-report/allureReport/*