image: gradle:alpine

#image: maven:3.9.9-openjdk-11

default:
  tags:
    - BackgroundAutoTestsAIM

stages:
  - ui
  - allure

UI Test:
  stage: ui
  allow_failure: true
  script:
    - ./gradlew -x test uiTests
  artifacts:
    paths:
      - build/allure-results

Allure report:
  stage: allure
  script:
    - ./gradlew allureReport
    - echo "Allure report live here"
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/*



#Integration tests with Allure:
#  stage: test
#  script:
#    - ./gradlew clean test
#  after_script:
#    - ./gradlew allureReport
#  artifacts:
#    when: always
#    paths:
#      - build/reports/allure-report/allureReport/*